#!/bin/bash
# Install kernel to test host
CONFIG=.vzt/kernel-install.cfg
function show_usage
{
	echo "$0: <host> [OPTS]"
	echo "Usage:"
	echo "Install kernele to test host via ssh or pxe"
	echo "Examples:"
	echo "Install kernel, modules and initrd to host via \
ssh and setup local boot loader"
	echo "	$0 my_host.org --all"
	echo "Install kernel only via ssh and setup local boot loader"
	echo "	$0 my_host.org "
	echo "Install kernel and setup pxe boot loader"
	echo "	$0 my_host --pxe"
	echo "Disable pxe boot  for host"
	echo "	$0 my_host --pxe --disable"
	
}	

if [ ! -f "$CONFIG" ]; then
	echo "Cant find .vzt/kernel-install.cfg"
	echo "you may use example config:"
	echo "  mkdir .vzt; cp /etc/vzt/kernel-install.cfg.example \
.vzt/kernel-install.cfg "
	exit
fi
. $CONFIG
krel=`make kernelrelease`

if [ ! $? -eq 0 ]; then
	echo "Can't get kernel release version"
	echo "This is probably happend CWD is wrong."
	echo "do: cd /your/path/to/kernel/linux-tree/"
	show_usage
	exit 1
fi
function SSH
{
	ssh -oStrictHostKeyChecking=no -oBatchMode=yes $@
	return $?
}

host="${1}"
shift
if [ -z "$host" ] ;then 
	echo "Err: Bad arguments"
	show_usage
	exit 1
fi
boot_proto=local
modules=y
mkinitrd=y
vmlinux=y
reboot=n
if [ "$1" = "--pxe" ]; then
	boot_proto="pxe"
	shift
fi

if [ "$1" = "--all" ]; then
	modules=y
	vmlinux=y
	mkinitrd=y
	shift
fi

if [ "$1" = "--suffix" ]; then
	shift
	krel=${krel}-${1}
	shift
fi

if [ "$1" = "--initrd" ]; then
	mkinitrd=y
	shift
fi

if [ "$1" = "--vmlinux" ]; then
	vmlinux=y
	shift
fi

if [ "$1" = "--reboot" ]; then
    reboot=y
fi

title="kernel-$krel"
echo "Install kernel to $server via protocol: $boot_proto"

##### pxe boot #####
if [ $boot_proto == "pxe" ] ;then
	echo "$BOOT_OPTS" | egrep "[^[:space:]]+"
	if [ $? -ne 0 ];then
		echo "Err: 'BOOT_OPTS' is empty. You must specify correct boot options"
		exit 1
	fi
	cp arch/$ARCH/boot/bzImage vmlinuz-$krel || exit 1
	vmlinuz-$krel root@$PXE_SERVER:/$PXE_ROOT/$PXE_KERNEL_DIR/vmlinuz-$krel \
		|| exit 1
	rm -f vmlinuz-$krel || exit 1
	SSH root@$PXE_SERVER " chmod 0444 /$PXE_ROOT/$PXE_KERNEL_DIR/vmlinuz-$krel"
	if [ $mkinitrd == "y" ]; then
		echo "Using initrd from different host is realy errorprone way."
		echo "kernel probably can't boot with this initrd image"
		scp initrd-$krel.img root@$PXE_SERVER:/$PXE_ROOT/$PXE_KERNEL_DIR || exit 1
		SSH root@$PXE_SERVER " chmod 0444 /$PXE_ROOT/$PXE_KERNEL_DIR/initrd-$krel.img "
	fi
	SSH root@$PXE_SERVER " vzt-pxe-boot $host add vmlinuz-$krel initrd-$krel.img '$BOOT_OPTS' $title"
	exit $?
fi

function grub_setup
{
	host=$1
	shift
	kernel_img=$1
	shift
	initrd_img=$1
	shift
	title_text=$1
	shift
	boot_opt=$@

	ssh root@${host} test  /boot/${kernel_img} || {
		echo "Kernel image : /boot/${kernel_img} not found";
		exit 1;
	}

	ssh root@${host} test /boot/${initrd_img} || {
		echo "initrd image :/boot/${initrd_img} not found" ;
		exit 1;
	}

	if [ -z "$boot_opt" ]; then
		args=--copy-default
	else
		args='--args=$boot_opt'
	fi
	SSH root@${host} grubby --remove-kernel=/boot/${kernel_img} \
				--add-kernel=/boot/${kernel_img} \
				--initrd=/boot/${initrd_img} \
				$args --title="${title_text}"
	ret=$?
	if [ $ret -ne 0 ] ;then
		echo "Error while grub setup"
	else
		echo "savedefault --default=0 --once" | \
				ssh root@$host "grub --batch > /dev/null"
		SSH root@$host " wall 'grub: ${kernel_img} --once'"
		SSH root@$host " echo 'grub: ${kernel_img} --once'  > /dev/kmsg"
		echo "grub setup OK"
	fi
	return $ret
}


##### local boot  #####
if [ $boot_proto == "local" ]; then
    	make tar-pkg
	#scp linux-$krel.tar.bz2 root@$host:/tmp/linux-$krel.tar.bz2 || exit 1

	cat linux-$krel.tar | SSH root@$host " tar mx  -C / " || exit 1
	SSH root@$host "echo 'new kernel and was intalled to /boot/vmlinuz-$krel' > /dev/kmsg"
	SSH root@$host "wall 'new kernel and was intalled to /boot/vmlinuz-$krel'"

	if [ $mkinitrd == "y" ]; then
	    SSH root@$host "depmod $krel"	        
	    SSH root@$host "mkinitrd \-f /boot/initrd-$krel.img $krel $MKINITRD_OPT" || exit 1
	fi
	grub_setup $host vmlinuz-$krel initrd-$krel.img $title $BOOT_OPTS

	if [ $reboot == "y" ]; then
	    SSH root@$host "reboot"	        
	fi


	#SSH root@$host " ls -l  "
	exit $?
fi
#################
echo "Bad boot protocol" ; 
exit 1

